#!/usr/bin/env bash
export GSI_CLUSTER=cluster1
export GSI_CONTEXT=$GSI_CLUSTER
export GSI_NETWORK=$GSI_CLUSTER

export GSI_MGMT_CLUSTER=$GSI_CLUSTER
export GSI_MGMT_CONTEXT=$GSI_CLUSTER
export GSI_MGMT_NETWORK=$GSI_CLUSTER

export SIDECAR_ENABLED=true
export SIDECAR_INJECTOR_WEBHOOKS_ENABLED=true
export MULTICLUSTER_ENABLED=true

export HELLOWORLD_ENABLED=true
export NETSHOOT_ENABLED=true
